name: Setup and Test

description: Common setup and test steps for all workflows

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup CI, Build and Test Package
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest
    - name: Debug pnpm environment
      run: |
        echo "PATH: $PATH"
        echo "NODE VERSION: $(node --version)"
        echo "NPM VERSION: $(npm --version)"
        echo "PNPM VERSION: $(pnpm --version)"
        which pnpm
        env | grep -E 'PNPM|NPM|NODE|PATH'
      shell: bash
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Run lint
      run: |
        if [ "$RUN_LINT" = "1" ]; then
          pnpm run lint
        else
          echo "Skipping lint. Set RUN_LINT=1 to enable."
        fi
      shell: bash
    - name: Run build
      run: |
        if [ "$RUN_BUILD" = "1" ]; then
          pnpm run build
        else
          echo "Skipping build. Set RUN_BUILD=1 to enable."
        fi
      shell: bash
    - name: Run tests
      run: |
        if [ "$RUN_TEST" = "1" ]; then
          pnpm vitest --coverage --reporter=verbose
        else
          echo "Skipping tests. Set RUN_TEST=1 to enable."
        fi
      env:
        SMOKE: 1
        DEBUG: 1
      shell: bash
