# Auto Merge PRs for stage/main after CI passes
# Maintainers: This workflow automates PR merges to 'stage' and 'main' after tests pass.
# Uses pascalgn/automerge-action for robust, label-free automerge.

# env
env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  
name: Auto Merge PRs

# Triggered by workflow call
on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write
  checks: read

concurrency:
  group: auto-merge-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  automerge:
    if: github.event.pull_request.base.ref == 'stage' || github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup (CI & Build) and Test Package
        uses: variablesoftware/github-actions-setup-and-test@main
      # - uses: ./.github/actions/setup-and-test
      - name: Automerge PR if CI passes
        uses: pascalgn/automerge-action@v0.16.4
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ''
          MERGE_FORKS: 'true'
          MERGE_RETRIES: '10'
          MERGE_RETRY_SLEEP: '60000'
          UPDATE_LABELS: ''
          UPDATE_METHOD: 'rebase'
          LOG: 'DEBUG'
