jobs:
  call-ci-release-sync:
    uses: variablesoftware/github-actions-setup-and-test/.github/workflows/ci-release-sync.yml@main
    with:
      # any workflow inputs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
      # any environment variables