jobs:
  call-auto-merge:
    uses: variablesoftware/github-workflows/.github/workflows/auto-merge.yml@main
    with:
      # any workflow inputs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
      # any environment variables
