env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
      - feature/**
      - bugfix/**
      - fix/**
      - hotfix/**
      - release/**
      - dependabot/**
      - renovate/**
      - chore/**
      - test/**

jobs:
  call-auto-merge:
    uses: variablesoftware/github-workflows/.github/workflows/auto-merge.yml@af4b71e7c65379fd7ce74592587fa8466ae7acfa
    # secrets:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

