on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
      - feature/**
      - bugfix/**
      - fix/**
      - hotfix/**
      - release/**
      - dependabot/**
      - renovate/**
      - chore/**
      - test/**

jobs:
  call-ci-release-sync:
    uses: variablesoftware/github-workflows/.github/workflows/ci-semantic-release-sync.yml@main
    # secrets:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
