# This workflow demonstrates how to call the reusable cleanup-branch workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'chore/**'
      - 'test/**'
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
    branches:
      - main
      - stage
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'chore/**'
      - 'test/**'

jobs:
  cleanup_branch:
    uses: variablesoftware/github-workflows/.github/workflows/cleanup-branch.yml@main
    with:
      commit_threshold: 10   # Optional, default is 10
      days_stale: 30        # Optional, default is 30
      base_branch: main     # Optional, default is 'main'
      dry_run: false        # Set to true for testing, false to actually open PRs
    secrets: inherit
