name: Call Auto Merge

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  RUN_TEST: 0
  RUN_BUILD: 0
  RUN_LINT: 0

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - stage
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'chore/**'
      - 'test/**'
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
    branches:
      - main
      - stage
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'chore/**'
      - 'test/**'

jobs:
  call-auto-merge:
    name: Call Auto Merge
    uses: variablesoftware/github-workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit


